services:
  - type: web
    name: trekking-site
    runtime: static
    buildCommand: "true"
    staticPublishPath: .
    routes:
      - type: redirect
        source: /
        destination: /code.html
